<?php

return [
    'app' => [
        'title' => 'General',
        'desc' => 'All the general settings for application.',
        'icon' => 'fas fa-cube',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'app_name',
                'label' => 'App Name',
                'rules' => 'required|min:2|max:50',
                'class' => '',
                'value' => 'Desa Dukuhlor',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'app_description',
                'label' => 'App Description',
                'rules' => 'nullable',
                'class' => '',
                'value' => 'Website resmi Pemerintah Desa Dukuhlor, Kecamatan Kuningan, Kabupaten Kuningan, Jawa Barat. Menyajikan informasi profil desa, layanan publik, berita, dan pengumuman.',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'footer_text',
                'label' => 'Footer Text',
                'rules' => 'required|min:2',
                'class' => '',
                'value' => '© '.date('Y').' Desa Dukuhlor. All rights reserved.',
            ],
            [
                'type' => 'checkbox',
                'data' => 'text',
                'name' => 'show_copyright',
                'label' => 'Show Copyright',
                'rules' => 'nullable',
                'class' => '',
                'value' => '1',
            ],
        ],
    ],
    'email' => [
        'title' => 'Email',
        'desc' => 'Email settings for app',
        'icon' => 'fas fa-envelope',

        'elements' => [
            [
                'type' => 'email',
                'data' => 'string',
                'name' => 'email',
                'label' => 'Email',
                'rules' => 'required|email',
                'class' => '',
                'value' => 'desa.dukuhlor@kuningankab.go.id',
            ],
        ],
    ],
    'social' => [
        'title' => 'Social Profiles',
        'desc' => 'Link of all the online/social profiles.',
        'icon' => 'fas fa-users',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'website_url',
                'label' => 'Website URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'facebook_url',
                'label' => 'Facebook Page URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'twitter_url',
                'label' => 'Twitter Profile URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'instagram_url',
                'label' => 'Instagram Account URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'youtube_url',
                'label' => 'Youtube Channel URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'linkedin_url',
                'label' => 'LinkedIn URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'whatsapp_url',
                'label' => 'WhatsApp URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
            [
                'type' => 'text',
                'data' => 'string',
                'name' => 'messenger_url',
                'label' => 'Messenger URL',
                'rules' => 'nullable|max:191',
                'class' => '',
                'value' => '#',
            ],
        ],
    ],
    'meta' => [
        'title' => 'Meta',
        'desc' => 'Application Meta Data',
        'icon' => 'fa-solid fa-earth-asia',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_site_name',
                'label' => 'Meta Site Name',
                'rules' => 'required',
                'class' => '',
                'value' => 'Desa Dukuhlor | Pemerintah Desa Dukuhlor',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_description',
                'label' => 'Meta Description',
                'rules' => 'nullable',
                'class' => '',
                'value' => 'Website resmi Pemerintah Desa Dukuhlor, Kecamatan Kuningan, Kabupaten Kuningan, Jawa Barat. Informasi profil desa, layanan publik, berita, dan pengumuman.',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_keyword',
                'label' => 'Meta Keyword',
                'rules' => 'nullable',
                'class' => '',
                'value' => 'desa dukuhlor, kuningan, jawa barat, pemerintah desa, profil desa, layanan publik, berita desa',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_image',
                'label' => 'Meta Image',
                'rules' => 'required',
                'class' => '',
                'value' => 'img/default_banner.jpg',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_fb_app_id',
                'label' => 'Meta Facebook App Id',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_twitter_site',
                'label' => 'Meta Twitter Site Account',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'meta_twitter_creator',
                'label' => 'Meta Twitter Creator Account',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
            ],
        ],
    ],
    'analytics' => [
        'title' => 'Analytics',
        'desc' => 'Application Analytics',
        'icon' => 'fas fa-chart-line',

        'elements' => [
            [
                'type' => 'text',
                'data' => 'text',
                'name' => 'google_analytics',
                'label' => 'Google Analytics (gtag)',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
                'help' => 'Paste the only the Measurement Id of Google Analytics stream.',
            ],
        ],
    ],
    'custom_css' => [
        'title' => 'Custom Code',
        'desc' => 'Custom code area',
        'icon' => 'fa-solid fa-file-code',

        'elements' => [
            [
                'type' => 'textarea',
                'data' => 'string',
                'name' => 'custom_css_block',
                'label' => 'Custom Css Code',
                'rules' => 'nullable',
                'class' => '',
                'value' => '',
                'help' => 'Paste the code in this field.',
                'display' => 'raw',
            ],
        ],
    ],
];
